{
 "title": "General Application Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Searched IPs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ip_search_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "% of searches with unique IP",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "unique_ip_search_count", "legendFormat": "Unique IPs" },
    {
     "expr": "ip_search_count-unique_ip_search_count",
     "legendFormat": "Repeat Requests"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_sessions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "session_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Time",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ip_search_duration_seconds_bucket",
     "legendFormat": "{{le}} s"
    }
   ]
  },
  {
   "title": "Unique searched IPs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "unique_ip_search_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IP Request Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "targets": [
    { "expr": "ip_search_error_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Result Locations",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \r\n\r\n    n.latitude,\r\n\r\n    n.longitude,\r\n\r\n    l.city_name\r\n\r\nFROM \r\n\r\n    geoip_network AS n\r\n\r\nJOIN \r\n\r\n    geoip_location AS l\r\n\r\nON \r\n\r\n    n.geoname_id = l.geoname_id\r\n\r\nWHERE \r\n\r\n    l.city_name IS NOT NULL\r\n\r\n    AND l.locale_code = 'en';"
    }
   ]
  }
 ]
}