- name: Download PostgreSQL Exporter
  get_url:
    url: "https://github.com/prometheus-community/postgres_exporter/releases/download/v{{ postgres_exporter_version }}/postgres_exporter-{{ postgres_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/postgres_exporter.tar.gz

- name: Extract PostgreSQL Exporter
  unarchive:
    src: /tmp/postgres_exporter.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy PostgreSQL Exporter binary
  copy:
    src: "/tmp/postgres_exporter-{{ postgres_exporter_version }}.linux-amd64/postgres_exporter"
    dest: /usr/local/bin/postgres_exporter
    remote_src: yes
    mode: 0755

- name: Create PostgreSQL Exporter configuration
  copy:
    dest: /etc/postgres_exporter.env
    content: |
      DATA_SOURCE_NAME="postgresql://{{ db_username }}:{{ db_password }}@localhost:5432/postgres?sslmode=disable"
    mode: 0600

- name: Create PostgreSQL Exporter systemd service
  copy:
    dest: /etc/systemd/system/postgres_exporter.service
    content: |
      [Unit]
      Description=PostgreSQL Exporter
      Wants=network-online.target
      After=network-online.target postgresql.service

      [Service]
      User=postgres
      Group=postgres
      Type=simple
      EnvironmentFile=/etc/postgres_exporter.env
      ExecStart=/usr/local/bin/postgres_exporter

      [Install]
      WantedBy=multi-user.target
    mode: 0644

- name: Enable and start PostgreSQL Exporter
  systemd:
    name: postgres_exporter
    state: started
    enabled: yes
    daemon_reload: yes

- name: Open PostgreSQL Exporter port in firewall
  ufw:
    rule: allow
    port: '9187'
    proto: tcp
